# Dataset and Path Configuration
batch_size: 128
accumulate_batch: 256
data_path: "data/im2latex100k"
img_path: "data/im2latex100k/formula_images_processed/formula_images_processed"
predict_img_path: "data/im2latex100k/formula_images_processed/formula_images_processed"
dataset: "100k"
vocab_file: "data/vocab/latex_tokens.json"

# Run Modes
train: true
val: false
test: false
predict: false
log_text: true

# Sample Sizes
train_sample: 75275
val_sample: 8370
test_sample: 10355

# Training Hyperparameters
cnn_channels: 32
enc_layers: 2
nhead: 16 
max_epochs: 30
log_step: 100
lr: 0.01
random_state: 42
ckpt_path: null
enc_type: "resnet_encoder"
enc_dim: 32
emb_dim: 80
attn_dim: 32
dec_dim: 32
dropout: 0.1
decode_type: "beamsearch"
beam_width: 5
num_layers: 4
model_name: "image_to_latex"
grad_clip: 0.5
num_workers: 0
gpu: true
devices: 1
strategy: "auto"
rewrite_checkpoint_fitting: false
checkpoints_path: "checkpoints"
tb_logs_path: "tb_logs"

