defaults:
  - _self_


hsv_h: 0.0      # Изменение оттенка (Hue)
hsv_s: 0.0        # Изменение насыщенности
hsv_v: 0.0        # Изменение яркости
degrees: 0.1      # Поворот
translate: 0.1    # Сдвиг по X и Y
scale: 0.5        # Масштабирование
shear: 0.1        # Сдвиг срезом
perspective: 0.0  # Искажение перспективы
flipud: 0.0       # Вертикальное отражение
fliplr: 0.0       # Горизонтальное отражение
mosaic: 0.5       # Mosaic-аугментация (4 изображения в одно)
mixup: 0.1        # Mixup-аугментация
erasing: 0.1      # Random Erasing
