defaults:
  - _self_

data: "../datasets/experiment/dataset.yaml"
epochs: 120
imgsz: 500
seed: 42
device: all
batch: 1024
verbose: false
dropout: 0.5
augment: true
name_prefix: "yolo11pt"
rect: true
plots: true
visualize: true
project: "latex"
